### PR TITLE
Javadoc fixes

### PR DESCRIPTION
**Pull request by snazy**

### CODE REVIEW

**Review by RussellSpitzer — COMMENTED** [review]
javadoc is still failing for me right now,
Looks like we still have a bunch of broken things

```
 5 errors
100 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':polaris-core:javadoc'.
```

Did I miss something here?

**Comment by RussellSpitzer** [comment]
> Warnings - yea. This PR is meant to fix the actual errors.

5 - Errors, the compilation fails

**Comment by snazy** [comment]
Argh - javadoc issues in generated OpenAPI code. Not much we can do about that, so excluding that error.

**Comment by snazy** [comment]
Note: a CI step for that comes via #190

**Review by RussellSpitzer — APPROVED** [review]
Looks good to me now, Javadoc building fine as well.

**Pull request merged**
