### PR TITLE
Upgrade to Apache Iceberg 1.6.1

### LINKED ISSUE #5: Upgrade to Apache Iceberg 1.6.0

### PR DESCRIPTION
**Pull request by jbonofre**
Fixes #5

### CODE REVIEW

**Review by RussellSpitzer — DISMISSED** [review]

**Comment by jbonofre** [comment]
@RussellSpitzer afair some tests were failing, I gonna fix that 😄

**Comment by flyrain** [comment]
This could be dangerous based on how much Polaris depends on Iceberg and the changes between iceberg 1.5 and 1.6. I'd suggest people who are familiar with the Polaris tests coverage to take a look. Just in case we hit any issue, esp. seder related ones.

**Comment by jbonofre** [comment]
@flyrain I'm investigating, I think I found the problem 😄

**Comment by jbonofre** [comment]
I'm resuming my work on this one, also rebasing.

**Comment by jbonofre** [comment]
I found that the tests failure are related to this change in Apache Iceberg:

```
commit 24d26b6a35a1287531e72357691d9dbd3d7f79bd                                                                                                                                                                                                                                 
Author: dongwang <mingwbd@gmail.com>                                                                                                                                                                                                                                            
Date:   Fri Jul 5 15:08:44 2024 +0800                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                
    Core: Fix create v1 table on REST Catalog (#10369)                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                
    Co-authored-by: Amogh Jahagirdar <amoghj@apache.org> 
```

I suspect it's about the table version. I will update Polaris to deal with this Iceberg fix.

**Comment by jbonofre** [comment]
I confirm commit `24d26b6a35a1287531e72357691d9dbd3d7f79bd` introduce the tests failure.
The problem is about the default version created. I'm fixing.

**Comment by dimas-b** [comment]
@jbonofre : I believe the test failures in `PolarisRestCatalogIntegrationTest` are mere catalog name clashes because the new iceberg test is parameterized, which is not expected by `PolarisRestCatalogIntegrationTest.before()`, which uses `currentCatalogName = method.getName()`.

I was thinking of just adding a counter to the method name.

We could try and delete old catalogs after each test, but it seems to be too involved for an Iceberg version bump due to emptiness checks on delete.

**Comment by jbonofre** [comment]
@dimas-b it's both. I saw the namespace issue but I can confirm that the default version in table metadata cause tests failure as well.

**Comment by dimas-b** [comment]
hmmm.... I ran that test locally yesterday and it passed with just fixing the catalog name to be unique.

**Review by dimas-b — APPROVED** [review]
LGTM :) Thanks, @jbonofre !

**Comment by dimas-b** [comment]
CC: @snazy for a binding +1 :)

**Review by snazy — APPROVED** [review]

**Pull request merged**
