### PR TITLE
Source tarball - include file name in digest file

### PR DESCRIPTION
**Pull request by snazy**
Also fix two related Gradle deprecations

### CODE REVIEW

**Comment by jbonofre** [comment]
It's the same as https://github.com/apache/polaris/pull/474 right ?

**Comment by snazy** [comment]
> It's the same as #474 right ?

Um - I thought that was already merged, failed to find it in the code base - and opened this one :disappear:

**Comment by jbonofre** [comment]
@snazy no problem at all ! Thanks for the PR !

**Review by jbonofre — COMMENTED** [review]
@snazy  Can you please also rename `sha512` to `tar.gz.sha512` ?

**Comment by snazy** [comment]
Already done

**Review by jbonofre — APPROVED** [review]

**Pull request merged**
