### PR TITLE
Add initial `.asf.yaml`

### PR DESCRIPTION
**Pull request by snazy**
Based on #174, with the PR comments applied.

### CODE REVIEW

**Comment by jbonofre** [comment]
Why creating a new one whereas we have the other PR ? I'm creating the mailing lists btw.

**Comment by snazy** [comment]
I don't mind using your PR - just that there's more stuff in there

**Comment by jbonofre** [comment]
@snazy let me remove `.asf.yml` from my other PR and use yours. We need to wait the mailing lists created (request submitted) before merging (ok, we can't merge anything for now 😄 ).

**Review by jbonofre — APPROVED** [review]

**Pull request merged**
