### PR TITLE
Add maven local by default in order to test local build (especially for Apache Iceberg)

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Review by snazy — CHANGES_REQUESTED** [review]
`mavenLocal()` comes with a bunch of drawbacks. In particular it slows down the build and it prevents Gradle from verifying that dependencies come from the "right" source (repository validations don't work).

I'd propose two changes here:
1. Make the addition of `mavenLocal()` dependent on a system or project property ([example here](https://github.com/projectnessie/nessie/blob/383bb67e471205d46ca670695d15e99818ccc089/settings.gradle.kts#L32-L34)). No need to slow down the build for everyone.
2. Use Gradle included builds - include the Iceberg build into the Polaris build. Then you also get all the benefits of Gradle and can skip the publishing step entirely. It also allows debugging into the Iceberg code.

**Comment by jbonofre** [comment]
@snazy thanks ! I will update the PR according to your comments.

**Comment by jbonofre** [comment]
@snazy just to be sure, by "included builds", you mean using `--include-build` arg right ?

**Comment by snazy** [comment]
> @snazy just to be sure, by "included builds", you mean using `--include-build` arg right ?

Either this - or in the build scripts - the result's the same

**Pull request closed without merging**
