### PR TITLE
Update README.md to use Apache Polaris TM

### PR DESCRIPTION
**Pull request by justinmclean**
# Description

Fix name and trademark as per ASF policy

Fixes # N/A

## Type of change

Please delete options that are not relevant.

- [X] This change requires a documentation update

# How Has This Been Tested?

N/A

# Checklist:

Please delete options that are not relevant.

N/A

### CODE REVIEW

**Review by ebyhr — APPROVED** [review]

**Comment by jbonofre** [comment]
@justinmclean I'm not sure Polaris trademark has been registered already. Do we need it now ? I think we register for graduation right ?

**Review by jbonofre — APPROVED** [review]

**Comment by justinmclean** [comment]
That's why I used the TM symbol rather than the R symbol, as it is not, AFAIK, a registered trademark.

**Comment by justinmclean** [comment]
Basically a TM says it's the ASF's brand with no need to register it.

**Comment by snazy** [comment]
> Basically a TM says it's the ASF's brand with no need to register it.

Agree, AFAIK yes, `TM` says it's a trademark, just unregistered.

**Pull request merged**
