### PR TITLE
Bump Gradle to 8.11

### PR DESCRIPTION
**Pull request by snazy**

### CODE REVIEW

**Comment by snazy** [comment]
@jbonofre wonder whether Renovate doesn't run

**Comment by jbonofre** [comment]
Yeah. Good point. I forgot to check. I will do it tomorrow (Nov 11 is holiday in France)

**Comment by jbonofre** [comment]
rat is complaining in this PR. Let me double check why (I think it's unrelated to this change).

**Comment by jbonofre** [comment]
Rat is complaining due to temporary file created by Gradle 8.11 for kotlin compiler.

I'm pushing a fix commit (excluding kotlin-compiler from rat check) on this PR.

**Review by adutra — APPROVED** [review]

**Pull request merged**
