### PR TITLE
Upgrade to Gradle 8.11.1

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Review by adutra — APPROVED** [review]

**Review by snazy — CHANGES_REQUESTED** [review]
Can you also fix these new deprecations:
```
w: file:///.../build-logic/src/main/kotlin/publishing/MemoizedGitInfo.kt:38:19 'exec(Action<in ExecSpec!>): ExecResult' is deprecated. Deprecated in Java
w: file:///.../build-logic/src/main/kotlin/publishing/rootProject.kt:52:9 'exec(Action<in ExecSpec!>): ExecResult' is deprecated. Deprecated in Java
```

**Comment by jbonofre** [comment]
@snazy good call ! I'm tackling that 😄

**Comment by snazy** [comment]
https://github.com/projectnessie/nessie/pull/9965 might help as a  blueprint

**Review by snazy — APPROVED** [review]
We also need #492 though - it's sometime a bit challenging :(

**Pull request merged**
