### PR TITLE
Update license header templates + replace in files

### PR DESCRIPTION
**Pull request by snazy**

### CODE REVIEW

**Comment by snazy** [comment]
This is based on #170

/cc @jbonofre

**Comment by jbonofre** [comment]
Cool. Let me take a look. Thanks !

**Comment by snazy** [comment]
@RussellSpitzer @takidau @annafil can you approve?

**Review by takidau — APPROVED** [review]
LGTM, thank you!

**Review by jbonofre — APPROVED** [review]

**Comment by snazy** [comment]
Thanks @takidau !

**Pull request merged**
