### PR TITLE
Fix javadoc in OpenAPI generated code

### PR DESCRIPTION
**Pull request by dimas-b**
Fix the mustache pattern to do HTML escaping for special chars in javadoc (do not use tripple `{{{`).

Original warning:

```
> Task :polaris-service:javadoc
/home/.../polaris-service/build/generated/src/main/java/org/apache/polaris/service/catalog/api/IcebergRestCatalogApi.java:489: warning: invalid input: '<'
   * Load a table from the catalog.  The response contains both configuration and table metadata. The configuration, if non-empty is used as additional configuration for the table that overrides catalog configuration. For example, this configuration may change the FileIO implementation to be used for the table.  The response also contains the table's full metadata, matching the table metadata JSON file.  The catalog configuration may contain credentials that should be used for subsequent requests for the table. The configuration key \"token\" is used to pass an access token to be used as a bearer token for table requests. Otherwise, a token may be passed using a RFC 8693 token type as a configuration key. For example, \"urn:ietf:params:oauth:token-type:jwt=<JWT-token>\".
```

### CODE REVIEW

**Comment by eric-maynard** [comment]
Can we consider instead making this fix in the upstream [Iceberg spec](https://github.com/apache/iceberg/blob/02a988b09ab5b6e9aaa47c79e5e131313cf983cc/open-api/rest-catalog-open-api.yaml#L930)?

**Comment by flyrain** [comment]
> Can we consider instead making this fix in the upstream [Iceberg spec]?

We should do that, otherwise, the issue will come back next time Polaris syncs the Iceberg rest spec.

**Comment by dimas-b** [comment]
Upstreaming is not necessary. The pattern turned out to be local to Polaris, but it was using the unescaped way of including "notes".

**Review by sfc-gh-emaynard — APPROVED** [review]
LGTM, good catch! Perhaps we should adjust the PR description / name based on the refactor.

**Review by eric-maynard — APPROVED** [review]
LGTM, good catch! Perhaps we should adjust the PR description / name based on the refactor.

**Comment by dimas-b** [comment]
The PR description has been updated, indeed.

**Comment by eric-maynard** [comment]
Nice! I think since we aren't changing any javadoc anymore the title might still be misleading. Either way, LGTM

**Comment by dimas-b** [comment]
_Generated_ javadoc is change by virtue of changing the pattern that generates it.

**Review by collado-mike — APPROVED** [review]

**Pull request merged**
